drop table if exists blog;
drop table if exists blog_post;
drop table if exists blog_user;
drop table if exists comment;
drop table if exists platform_role;
drop table if exists platform_user;
drop table if exists platform_role_user;

CREATE TABLE BLOG (ID INTEGER IDENTITY NOT NULL, BLOG_NAME varchar,  BLOG_USER_ID INTEGER, VERSION INTEGER, CREATE_DATE DATE, UPDATE_DATE DATE, PRIMARY KEY (ID));
CREATE TABLE BLOG_POST (ID INTEGER IDENTITY NOT NULL, POSTTEXT TEXT, BLOG_ID INTEGER, VERSION INTEGER, CREATE_DATE DATE, UPDATE_DATE DATE, PRIMARY KEY (ID));
CREATE TABLE BLOG_USER (ID INTEGER IDENTITY NOT NULL, FIRSTNAME VARCHAR, LASTNAME VARCHAR, EMAIL VARCHAR, PLAT_USER_ID INTEGER, VERSION INTEGER, CREATE_DATE DATE, UPDATE_DATE DATE, PRIMARY KEY (ID));
CREATE TABLE COMMENT (ID INTEGER IDENTITY NOT NULL, COMMENT_TEXT VARCHAR, VERSION INTEGER, OWNING_USER_ID INTEGER,  POST_ID INTEGER, CREATE_DATE DATE, UPDATE_DATE DATE, PRIMARY KEY (ID));
CREATE TABLE PLATFORM_ROLE (ID INTEGER IDENTITY NOT NULL, ROLENAME VARCHAR, VERSION INTEGER, CREATE_DATE DATE, UPDATE_DATE DATE, PRIMARY KEY (ID));
CREATE TABLE PLATFORM_USER (ID INTEGER IDENTITY NOT NULL, USERNAME VARCHAR, PWDHASH VARCHAR, VERSION INTEGER, CREATE_DATE DATE, UPDATE_DATE DATE, PRIMARY KEY (ID));
CREATE TABLE PLATFORM_ROLE_USER (USER_ID INTEGER NOT NULL, ROLE_ID INTEGER NOT NULL, PRIMARY KEY (USER_ID, ROLE_ID));
ALTER TABLE BLOG_POST ADD CONSTRAINT FK_BLOG_POST_BLOG_ID FOREIGN KEY (BLOG_ID) REFERENCES BLOG (ID);
ALTER TABLE BLOG ADD CONSTRAINT FK_BLOG_BLOG_USER_ID FOREIGN KEY (BLOG_USER_ID) REFERENCES BLOG_USER (ID);
ALTER TABLE BLOG_USER ADD CONSTRAINT FK_BLOG_PLAT_USER_ID FOREIGN KEY (PLAT_USER_ID) REFERENCES PLATFORM_USER (ID);
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_USER_ID FOREIGN KEY (OWNING_USER_ID) REFERENCES BLOG_USER (ID);
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_POST_ID FOREIGN KEY (POST_ID) REFERENCES BLOG_POST (ID);
ALTER TABLE PLATFORM_ROLE_USER ADD CONSTRAINT FK_PLATFORM_ROLE_USER_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES PLATFORM_ROLE (ID);
ALTER TABLE PLATFORM_ROLE_USER ADD CONSTRAINT FK_PLATFORM_ROLE_USER_USER_ID FOREIGN KEY (USER_ID) REFERENCES PLATFORM_USER (ID);
INSERT INTO PLATFORM_USER VALUES('ADMIN', 'ADMIN');
INSERT INTO PLATFORM_ROLE VALUES('USER');

